# Setup
title:        Swee Lim's website and Github repo
tagline:      Welcome, here you will find links to my research, code and bio.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Swee Lim
  url:        http://moosekaka.github.io

# Gems
gems: [jekyll-paginate]

#Others
markdown: redcarpet